### ISSUE TITLE
Links and pointers to implement inserts/updates/deletes/etc.

### ISSUE THREAD

**Issue by iamnewspecies** [rfink/sequelize-redis-cache#10]
Please provide some data on how to implement inserts/updates/deletes/etc. Links to existing information on this topic would be great. Meanwhile I am googling it.

**Comment by rfink** [comment]
Hello, and thanks for commenting.  Right now, there is no way in this module to handle inserts/updates/deletes, in terms of cache-busting (I'm thinking that's why you're asking, correct?)  I had originally considered it, but the implications are deep, since the module allows deeply customizable queries.  So, it would be relatively easy to bust a fetchById type query, but not so much a "fetchAll".  This is a very difficult topic, the only applications that I know of that do this are:

MySQL query cache (since it is the data set authority)
Systems that handle OLAP and XMLA type querying

Does that make sense?
