### ISSUE TITLE
Update cache on sequelize update data for key.

### ISSUE THREAD

**Issue by devdavidkarlsson** [rfink/sequelize-redis-cache#24]
I am missing the update functionality:

When a object is created/updated I want it to be cached immediately.
Not only on search/find..

**Comment by rfink** [comment]
Hello and thanks for checking out my module. I have considered this idea in the past, and decided that in order to add a fully transactional cache model, the module would need to be completely overhauled and integrated as a plugin to sequelize. Also, one complication here is the issue of aggregate queries that touch created/updated items.  It would be extremely complex to coordinate  busting aggregate cache keys.  If anyone had an idea on a simple way to do this, I would be open to accepting a pull request.
